<a href="https://colab.research.google.com/github/barcellfe/datascience_study/blob/master/Alua_28-10_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas:

Assim como o numpy, importamos o pandas como pd

In [ ]:
import pandas as pd
from pandas import Series, DataFrame

In [ ]:
dicionario = {'Nome': ['Jhean', 'Carla', 'Maria', 'Clara', 'Laura'], 
              'Idade': [33, 32, 36, 49, 60],
              'Cidade': ['Sorocaba', 'São Paulo', 'Rio de Janeiro', 'São Paulo', 'Guarulhos']}

dicionario
              

{'Cidade': ['Sorocaba',
  'São Paulo',
  'Rio de Janeiro',
  'São Paulo',
  'Guarulhos'],
 'Idade': [33, 32, 36, 49, 60],
 'Nome': ['Jhean', 'Carla', 'Maria', 'Clara', 'Laura']}

<function dict.values>

In [ ]:
dicionario['Cidade']

['Sorocaba', 'São Paulo', 'Rio de Janeiro', 'São Paulo', 'Guarulhos']

In [ ]:
dicionario['Idade'][0]

33

In [ ]:
##Declaração de uma série:

pd.Series([10, 20, 30, 40, 50, 60])

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [ ]:
pd.Series([10, 20, 30, 40, 50, 60], index = ['lab1', 'lab2', 'lab3', 'lab4', 'lab5', 'lab6'])

lab1    10
lab2    20
lab3    30
lab4    40
lab5    50
lab6    60
dtype: int64

In [ ]:
obj = pd.Series([10, 20, 30, 40, 50, 60], index = ['lab1', 'lab2', 'lab3', 'lab4', 'lab5', 'lab6'])
obj.values

array([10, 20, 30, 40, 50, 60])

In [ ]:
obj.values

array([10, 20, 30, 40, 50, 60])

In [ ]:
obj.index

Index(['lab1', 'lab2', 'lab3', 'lab4', 'lab5', 'lab6'], dtype='object')

In [ ]:
obj['lab6']

60

In [ ]:
obj > 10

lab1    False
lab2     True
lab3     True
lab4     True
lab5     True
lab6     True
dtype: bool

In [ ]:
obj[obj == 10]

lab1    10
dtype: int64

In [ ]:
sdata = {'Ohio': 3500, 'Texas': 7100, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio       3500
Texas      7100
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj3.values[0][0]

3500

In [ ]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas          7100.0
dtype: float64

In [ ]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
obj3

Ohio       3500
Texas      7100
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas          7100.0
dtype: float64

In [ ]:
obj3 + obj4

California        NaN
Ohio           7000.0
Oregon        32000.0
Texas         14200.0
Utah              NaN
dtype: float64

In [ ]:
##reindexação

obj

lab1    10
lab2    20
lab3    30
lab4    40
lab5    50
lab6    60
dtype: int64

In [ ]:
obj.index = ['Bob', 'Steve', 'Elvis', 'Ozzy', 'Jeff', 'Ryan']
obj

Bob      10
Steve    20
Elvis    30
Ozzy     40
Jeff     50
Ryan     60
dtype: int64

In [ ]:
##Criação de DataFrame

data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002,2001,  2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data, index = ['v1', 'v2', 'v3', 'v4', 'v5', 'v6'])
frame

state  year  pop
v1    Ohio  2000  1.5
v2    Ohio  2001  1.7
v3    Ohio  2002  3.6
v4  Nevada  2001  2.4
v5  Nevada  2002  2.9
v6  Nevada  2003  3.2

In [ ]:
frame.describe()

year       pop
count     6.000000  6.000000
mean   2001.500000  2.550000
std       1.048809  0.836062
min    2000.000000  1.500000
25%    2001.000000  1.875000
50%    2001.500000  2.650000
75%    2002.000000  3.125000
max    2003.000000  3.600000

In [ ]:
frame.head(3)

state  year  pop
v4  Nevada  2001  2.4
v5  Nevada  2002  2.9
v6  Nevada  2003  3.2

In [ ]:
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003]}

In [ ]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                      index = ['one', 'two', 'three', 'four', 'five', 'sex'])

frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
sex    2003  Nevada  3.2  NaN

In [ ]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
frame2['pop']

one      1.5
two      1.7
three    3.6
four     2.4
five     2.9
sex      3.2
Name: pop, dtype: float64

In [ ]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'sex'], dtype='object')

In [ ]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [ ]:
frame.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [ ]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [ ]:
frame2['debt']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
sex      NaN
Name: debt, dtype: object

In [ ]:
frame2['debt'] = 16.5

In [ ]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
sex    2003  Nevada  3.2  16.5

In [ ]:
frame

state  year  pop  debt
0    Ohio  2000  1.5  16.5
1    Ohio  2001  1.7  16.5
2    Ohio  2002  3.6  16.5
3  Nevada  2001  2.4  16.5
4  Nevada  2002  2.9  16.5
5  Nevada  2003  3.2  16.5

In [ ]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
sex    2003  Nevada  3.2   5.0

In [ ]:
frame2.loc[frame2['year'] == 2003, 'debt'] = 50
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
sex    2003  Nevada  3.2  50.0

In [ ]:
global_store = pd.read_excel('Global Superstore.xls')
global_store.head()

Row ID         Order ID Order Date  ...    Profit Shipping Cost Order Priority
0   32298   CA-2012-124891 2012-07-31  ...  762.1845        933.57       Critical
1   26341    IN-2013-77878 2013-02-05  ... -288.7650        923.63       Critical
2   25330    IN-2013-71249 2013-10-17  ...  919.9710        915.49         Medium
3   13524  ES-2013-1579342 2013-01-28  ...  -96.5400        910.16         Medium
4   47221     SG-2013-4320 2013-11-05  ...  311.5200        903.04       Critical

[5 rows x 24 columns]